# description
name: "grjs"
description: "A javascript test exercise."
keywords: "javascript, tdd, vanilla, css4"
author: "Leszek Pietrzak"

# address settings
baseurl: "http://grjs.smutnyleszek.com"

# site configuration
safe: true
quiet: false
future: true
encoding: utf-8
markdown: kramdown
kramdown:
    auto_ids: false
timezone: Europe/Warsaw

# misc
fontUrl: "https://fonts.googleapis.com/css?family=PT+Sans:400,700&subset=latin,latin-ext"

# excludes
exclude:
    - node_modules
    - exercise-files
    - Gruntfile.js
    - package.json
